export const threatData = state => state.threatData
export const wordList = state => state.wordList
export const geneFamily = state => state.geneFamily
export const point = state => state.point
export const detectionResult = state => state.detectionResult
export const sampleDetection = state => state.sampleDetection
export const sampleAnalysis = state => state.sampleAnalysis
export const attackTypeData = state => state.attackTypeData
export const search = state => state.search
export const detQueue = state => state.detQueue
export const undetectSample = state => state.undetectSample
export const sampleReport = state => state.sampleReport
export const allLable = state => state.allLable
export const sampleTags = state => state.sampleTags
export const aptFamily = state => state.aptFamily
export const analysisReportData = state => state.analysisReportData
export const analysisReportDetailData = state => state.analysisReportDetailData
export const activeCountry = state => state.activeCountry
export const setFileImportLevel = state => state.setFileImportLevel
