export const setAuthEdit = (state, val) => { state.editAuth = Boolean(val) }
export const threatData = (state, value) => { state.threatData = value }
export const wordListData = (state, value) => { state.wordList = value }
export const geneFamilyData = (state, value) => { state.geneFamily = value }
export const pointData = (state, value) => { state.point = value }
export const detectionResultData = (state, value) => { state.detectionResult = value }
export const sampleDetectionData = (state, value) => { state.sampleDetection = value }
export const sampleAnalysisData = (state, value) => { state.sampleAnalysis = value }
export const attackTypeData = (state, value) => { state.attackTypeData = value }
export const searchData = (state, value) => { state.search = value }
export const detQueueData = (state, value) => { state.detQueue = value }
export const UndetectSampleData = (state, value) => { state.undetectSample = value }
export const sampleReport = (state, value) => { state.sampleReport = value }
export const allLable = (state, obj) => { state.allLable = obj }
export const sampleTags = (state, obj) => { state.sampleTags = obj }
export const aptFamily = (state, obj) => { state.aptFamily = obj }
export const analysisReportData = (state, value) => { state.analysisReportData = value }
export const analysisReportDetailData = (state, value) => { state.analysisReportDetailData = value }
export const getActiveCountry = (state, value) => { state.activeCountry = value }
export const setFileImportLevel = (state, obj) => { state.setFileImportLevel = obj }
